name:                hatexmt
version:             0.1.0.0
github:              "githubuser/hatexmt"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hatexmt#readme>

default-extensions:
    - OverloadedStrings
    - BlockArguments

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - req >= 3.9
    - aeson >= 1.5
    - HaTeX
    - bytestring
    - text >= 1.2
    - html-entities
  

executables:
  hatexmt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hatexmt
      - HaTeX
      - text >= 1.2
      - req >= 3.9
      - aeson >= 1.5
      - bytestring
    default-extensions:
      - OverloadedStrings


tests:
  hatexmt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hatexmt
    - filepath
    - text >= 1.2
    - hspec
